FROM mysql:latest
#ENV MYSQL_DATABASE smart-warehouse-database
#ENV MYSQL_ROOT_PASSWORD rootpassword
#ENV MYSQL_USER ADMIN
#ENV MYSQL_PASSWORD adminpassword
#ENV DATABASE_HOST smart-warehouse-backend

EXPOSE 3306

COPY ./sql-scripts /docker-entrypoint-initdb.d